name: Test

on:
  workflow_call:
  schedule:
  # run at 7:00 on the first of every month
  - cron: '0 7 1 * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.22"]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go ${{ matrix.go--version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: |
        go get .

    - name: Run unit tests
      run: |
        go test
